# Intro to R: A Hands on Tutorial {.unnumbered}

This book contains the materials for *Intro to R: A hands-on tutorial*, a multi-class R training initially created by the [Urban Institute R Users Group](https://urbaninstitute.github.io/r-at-urban/) and now presented to HUD staff by Ajjit Narayanan

Core lessons include:

1.  Data visualization

2.  Data munging (analysis)

3.  Getting data into and out of R

4.  Iteration

5.  Putting everything together

## Recordings

Some of the initial sessions had issues with recordings. So the linked recordings may be from an earlier year of the course but with pretty much the same content.


| Lesson | Recording Link |
|:-------|----------------|
| Day 0: Why Statistical Programming? |  [Link](https://us02web.zoom.us/rec/play/ctHtGaZbt_GNzUWHts9byWbJgx09MtEzohC0vP1XIBGI7NFLosA523eVZ0SeZkWlBDDM-af_DMUmw1JV.bk2OSIsMToaPRYNF?canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fus02web.zoom.us%2Frec%2Fshare%2F8YbXmIjZ5QQsHzCjCBGY8ySxvkdbdMSVqrEe24c2DvjnTNFlQudxNWY8aH9kSUsT.cWkx4dDdfv7gwPBW)|
| Day 1: Data Visualization |  [Link](https://us02web.zoom.us/rec/play/LheL1d4YSab7mEOlyv8kAqELs6uRg_GAFjqs9do6IHsn7VMb7sKONOZU4tbBRo244kJYnJEUKiVZXhMm.pYuGkv5_gwk_xA1P?canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fus02web.zoom.us%2Frec%2Fshare%2F2CPW6Bq1kiQ9vAB2fXRgj32jAoX-x1rI_r-ETblusjEUMZtM1gCBtHVj7Ghv1C2X.Abn5RTrHm1gS3Sa9) |
| Day 2: Data Munging I |  [Link](https://hudgov.sharepoint.com/:v:/s/OGrp-pliddataandanalytics/EeuDHT92SbpIpWR-H0vN_nABabpe5oCcuIeueYRi9m4ZTQ?e=MB3uGc&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZyIsInJlZmVycmFsQXBwUGxhdGZvcm0iOiJXZWIiLCJyZWZlcnJhbE1vZGUiOiJ2aWV3In19) |
| Day 3: Data Munging II |  [Link](https://hudgov.sharepoint.com/:v:/r/sites/fheo-oplio-plid590-AutomatingAFFHMaps/Shared%20Documents/Automating%20AFFH%20Maps/docs/quarto_recordings/Intro%20to%20R%20Classes-20231026_160318-Meeting%20Recording.mp4?csf=1&web=1&e=F7DkiQ&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D) |
| Day 4: Getting Data into and out of R |  [Link](https://hudgov.sharepoint.com/:v:/s/fheo-oplio-plid590-AutomatingAFFHMaps/EQfyQYCBtndEk5lg_H62gAYBqsjMuMtCiCMaricPnufW_Q?e=WaIVDP&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D) |
| Day 5: Iteration |  [Link](https://hudgov.sharepoint.com/:v:/s/fheo-oplio-plid590-AutomatingAFFHMaps/EWzd3RrD_U9Dverdl7lIXw4BUinV_UxWc7Heq7PEfIewlQ?e=Y3Omak&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D) |
| Day 6: Putting everything together |  [Link](https://hudgov.sharepoint.com/:v:/s/fheo-oplio-plid590-AutomatingAFFHMaps/EeDTtDzQnYlJoKIUjM4ec0QB0sPc7iuhn6EtJeGcvsKyVQ?e=R1ejxu&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D) |



## Questions?

Contact Ajjit Narayanan on Teams
